### PR TITLE
modify synthetic-protocol withdraw-liquidity

### LINKED ISSUE #51: ExistentialDeposit logic on liquidity pool is wrong
User cannot withdraw liquidity pool below ExistentialDeposit but protocol can.

https://github.com/laminar-protocol/laminar-chain/blob/b73f4082763dbf7ec5d01b0aaeb1fbbd87006de0/modules/liquidity-pools/src/lib.rs#L267-L270

### PR DESCRIPTION
**Pull request by zjb0807**
Closes #51

### CODE REVIEW

File: modules/liquidity-pools/src/lib.rs [hunk 1]
```diff
@@ -113,6 +113,14 @@ decl_module! {
 		pub fn withdraw_liquidity(origin, pool_id: T::LiquidityPoolId, amount: T::Balance) {
 			let who = ensure_signed(origin)?;
 			ensure!(Self::is_owner(pool_id, &who), Error::<T>::NoPermission);
+
+			let new_balance = Self::balances(&pool_id).checked_sub(&amount).ok_or(Error::<T>::CannotWithdrawAmount)?;
+
+			// check minimum balance
+			if new_balance < T::ExistentialDeposit::get() {
+				return Err(Error::<T>::CannotWithdrawAmount.into());
```
Comment (xlc) [inline modules/liquidity-pools/src/lib.rs]: Make a new error so user can know why this failed
